### PR TITLE
Allow save and load state to user the 'user://' location #10

### PR DESCRIPTION
**Pull request by lunarcloud**

### CODE REVIEW

**Comment by paulloz** [comment]
To be honest I think it'd be a better practice to always store that in `user://`.

**Comment by lunarcloud** [comment]
You never know when someone wants to offer a save file export or whatever. I think it's best to let the dev decide, but maybe falling back to user:// instead of calling back to res:// is a good idea?
Either way, current behavior of only res:// is not good

**Comment by paulloz** [comment]
But `res://` actually points to the game's install folder. It's quite weird writing stuff in here at runtime.

**Comment by lunarcloud** [comment]
So load might be okay from res, but save never is

**Comment by paulloz** [comment]
Yeah, not enforcing anything but falling back to `user://` seems fair to me 👍

**Comment by lunarcloud** [comment]
Shall I cancel the pull request?
Shall I redo the fix, or will you just fix it?

**Comment by paulloz** [comment]
You can replace the commit in this PR to change the fallback directory. If you're busy I'll do that later, no worries.

**Comment by lunarcloud** [comment]
first time doing pull requests. Think I did that right

**Comment by paulloz** [comment]
You're introducing tab indentation while we're using 4 spaces everywhere ⚠️.  
Appart from that, it's fine with me. I'll just squash your commits while merging.

**Comment by paulloz** [comment]
thanks 👍

**Pull request merged**
